version: "3.8"
services:
  backend:
    build: 
      context: ./server/
    container_name: backend_container
    ports:
      - "3005:3005"
    depends_on:
      - mongo
    networks:
      - mern-network
  
  frontend:
    build:
      context: ./client
    container_name: frontend_container
    ports: 
      - "3000:3000"
    networks:
      - mern-network
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
